http:
  port: 8080

db:
  mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: '123456'
    database: yrk_test

  redis:
    host: 127.0.0.1
    port: 6379
    family: 4
    password: ''
    db: 0,
    keyPrefix: 'hanser::'

